### ISSUE TITLE
SSO Authentication Method

### ISSUE THREAD

**Issue by AGSadovsky** [ibagomel/Visual-Flow#2]
In addition to current authentication methods lets consider a new one for SSO.

**Comment by mhaurylenka-gomel-iba-by** [comment]
SSO functionality implemented in release v0.9.19 https://github.com/ibagomel/Visual-Flow/releases/tag/v0.9.19
Configurable for any SSO provider, in particular, we have configured with Keycloak open source SSO tool.

**Comment by AGSadovsky** [comment]
Well done!
